In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')
df.head(5)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [15]:
Y=df.iloc[:,0]

In [16]:
X=df.iloc[:,1:]

In [17]:
Y.shape

(42000,)

In [18]:
df.shape

(42000, 785)

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)

In [21]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [22]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,confusion_matrix,classification_report

In [23]:
y_pred=knn.predict(x_test)

C:\Users\35454\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [24]:
accuracy_score(y_test,y_pred)

0.9639285714285715

In [26]:
precision_score(y_test,y_pred,average=None)

array([0.97136038, 0.957     , 0.98012422, 0.95119183, 0.9761621 ,
       0.9532967 , 0.97638725, 0.95475113, 0.98773842, 0.93601896])

In [27]:
recall_score(y_test,y_pred,average=None)

array([0.99147381, 0.99480249, 0.9517491 , 0.96990741, 0.9567757 ,
       0.95198903, 0.98569726, 0.96678121, 0.91424968, 0.94724221])

In [28]:
confusion_matrix(y_test,y_pred)

array([[814,   1,   2,   1,   0,   1,   2,   0,   0,   0],
       [  0, 957,   0,   2,   0,   0,   0,   2,   1,   0],
       [  4,   9, 789,   5,   0,   1,   3,  14,   2,   2],
       [  0,   2,   3, 838,   0,   8,   1,   6,   4,   2],
       [  1,  10,   0,   0, 819,   0,   2,   0,   0,  24],
       [  3,   0,   0,  16,   0, 694,   9,   0,   2,   5],
       [  7,   1,   0,   0,   1,   3, 827,   0,   0,   0],
       [  0,  12,   5,   0,   2,   0,   0, 844,   0,  10],
       [  3,   7,   5,  15,   2,  19,   3,   3, 725,  11],
       [  6,   1,   1,   4,  15,   2,   0,  15,   0, 790]], dtype=int64)

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       821
           1       0.96      0.99      0.98       962
           2       0.98      0.95      0.97       829
           3       0.95      0.97      0.96       864
           4       0.98      0.96      0.97       856
           5       0.95      0.95      0.95       729
           6       0.98      0.99      0.98       839
           7       0.95      0.97      0.96       873
           8       0.99      0.91      0.95       793
           9       0.94      0.95      0.94       834

    accuracy                           0.96      8400
   macro avg       0.96      0.96      0.96      8400
weighted avg       0.96      0.96      0.96      8400

